from .architecture_settings_dialog import ArchitectureSettingsDialog
from .inspection_settings_window import InspectionSettingsDialog
from .architecture_window import ArchitectureWindow
from .properties_window import PropertiesWindow
from .inspection_window import InspectionWindow
from .input_image_window import InputImageWindow

